name: quick-tests
run-name: Tests for Corth
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: sudo apt install python3
      - run: python3 PythonCompiler/main.py test -ceo
